# Generated by Django 6.0.4 on 2026-05-19 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_veterinario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='appvet.mascota'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='prioridad',
            field=models.CharField(default='Baja', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='appvet.veterinario'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas', to='appvet.cita'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='veterinario_nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
